# Generated by Django 4.2.10 on 2024-06-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_rendu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('localisation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SecretaireSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetapp.office')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_debut', models.DateTimeField()),
                ('session_fin', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='meets',
        ),
        migrations.AddField(
            model_name='participant',
            name='profession',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Meet',
        ),
        migrations.AddField(
            model_name='reunion',
            name='participant',
            field=models.ManyToManyField(related_name='reunions', to='meetapp.participant'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetapp.secretaireseance'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetapp.session'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='reunion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetapp.reunion'),
        ),
    ]
