# Generated by Django 4.2.10 on 2024-06-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0002_compterendu_office_reunion_secretaireseance_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, default='telechargement.png', null=True, upload_to='session_images/'),
        ),
    ]
