# Generated by Django 4.2.10 on 2024-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0003_session_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='participant',
            new_name='participants',
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='meetapp.participant'),
        ),
    ]
